name: Approved pull request

on:
  pull_request:
    types: closed
jobs:
  tag-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Label pr when approved
        uses: tiagonapoli/label-pr-on-merge@v0.0.2
        with:
          merged_label: "mergeau"
          branch: "main"
