name: Approved pull request

on:
  pull_request_review:
    types:
      - submitted
jobs:
  tag-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Label pr when approved
        uses: pullreminders/label-when-approved-action@main
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          ADD_LABEL: "approved"
